name: Build OmniLink
on:
  push:
    branches: [ omnilink-binding ]


jobs:
  build:
    # Using latest Ubuntu (not the GitHub Actions default) to get latest tool versions in GitHub Actions environment
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
         with:
           ref: ${{ github.ref }}
       - name: Cache local Maven repository
         uses: actions/cache@v2
         with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
           java-package: jdk
           architecture: x64
       - name: Install Maven
         run: sudo apt-get install maven
       - name: Build OmniLink Binding
         id: build
         run: |
           mvn -f bundles/org.openhab.binding.omnilink/pom.xml  -Dreport.fail.on.error=false -B install
           echo "::set-output name=file::$(ls bundles/org.openhab.binding.omnilink/target/org.openhab.binding.omnilink-*-SNAPSHOT.jar | sed 's|bundles/org.openhab.binding.omnilink/target/||')"
       - name: Archive
         uses: actions/upload-artifact@v2
         with:
           name: ${{ steps.build.outputs.file }}
           path: bundles/org.openhab.binding.omnilink/target/org.openhab.binding.omnilink-*-SNAPSHOT.jar
